### ISSUE TITLE
Place bulbs side by side on mobile

### ISSUE THREAD

**Issue by kamakshidasan** [QwertyWorks/qwertyworks.github.io#11]
Could you make the bulbs be placed next to each other on the mobile version?

**Comment by cruzer3008** [comment]
Done !!

**Comment by kamakshidasan** [comment]
The same for app buttons as well?

The first time I click on the buttons, they seem to reduce in size. I think this is because you shoot a query to the server for the other image only after clicking.

One probable way to fix this would be prefetch all images at the start of the website.

**Comment by cruzer3008** [comment]
App button also placed side by side.....

Which buttons do you imply ??
Also we added pre-fetching of the bulb images in the product section ( Like on hovering upon the bulb image a lit bulb shows up . However that used to take up some time to load. Thus we fixed that issue by adding a java-script function
`function preloadImage(url)
{
    var img=new Image();
    img.src=url;
}`
and hosting those couple of images online on imgur)
Please tell us if the issue of size reduction still prevails.

**Comment by kamakshidasan** [comment]
Okay. Good - your way is correct.

Why imgur? Isn't hosting on Github enough?

**Comment by cruzer3008** [comment]
I tried using the github link but somehow it is not showing the image.
Thus resorted to imgur

**Comment by kamakshidasan** [comment]
Interesting. We don't want to have too many dependencies. Getting the job is definitely one aspect, but doing the best way is a primary focus.

I will leave this issue open. Get back to me when you know why Github fails to show the image.

**Comment by cruzer3008** [comment]
Issue solved...
It's weird though..
The thing is that neither is the link [qwertyworks.github.io/Interns/js/images/leftback.png](url) working when put in the css file and in the js file ( for preloaing function )  (P.S this is the link which you get when you press on the copy path button ) , nor is the link [https://github.com/QwertyWorks/qwertyworks.github.io/blob/master/Interns/js/images/leftback.png](url) working (this is the page link) . 
However the link [https://raw.githubusercontent.com/QwertyWorks/qwertyworks.github.io/master/Interns/js/images/leftback.png](url) is working. This is the link which you get when you right click on the image and open the image in a new tab

**Comment by cruzer3008** [comment]
Issue solved...
It's weird though..
The thing is that neither is the link [obtained from pressing the copy path button](qwertyworks.github.io/Interns/js/images/leftback.png) working when put in the css file and in the js file ( for preloading function ) nor is the [page link](https://github.com/QwertyWorks/qwertyworks.github.io/blob/master/Interns/js/images/leftback.png ) 
However the link [which you get when you right click on the image and open the image in a new tab](https://raw.githubusercontent.com/QwertyWorks/qwertyworks.github.io/master/Interns/js/images/leftback.png) is working

**Comment by kamakshidasan** [comment]
Interesting.

Small suggestion - whenever you want to use raw.githubusercontent.com/* you can instead use this website: https://rawgit.com/ and use the production option for images that will not change anytime in the future.

**Comment by kamakshidasan** [comment]
@cruzer3008 : Can I close this issue?

**Comment by cruzer3008** [comment]
The bulbs have been placed side by side 

Regarding hosting the images online we will do in the end for all the images because still we aren't sure of what images to be kept where and also might add of remove some images...
Plus compressing them would also lead to a new path

**Comment by anant-QwertyWorks** [comment]
Makes sense

Sent from my iPhone

On 02-Aug-2018, at 11:38, Yash Khakhar <notifications@github.com> wrote:

The bulbs have been placed side by side

Regarding hosting the images online we will do in the end for all the images because still we aren't sure of what images to be kept where and also might add of remove some images...
Plus compressing them would also lead to a new path
