### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by kamakshidasan** [QwertyWorks/qwertyworks.github.io#17]
I just took a look at the video. It's about 30 seconds long and displays almost all colours. It's definitely good. @cruzer3008, @maitri0411 Can you link the CSS file here that is used to induce the opacity/transparency? I think if you reduce that, it should look way more "natural".

Also,  I feel that you don't have to show all colors here. Just few "nice" colours should work. Instead of playing with the colorwheel on the app, look at transition effects. Example: https://www.youtube.com/watch?v=xVyi2ttBI14

Instead of a bulb, can you show a room illuminated with different colours on different occasions? Maroon for romance, orange for diwali, sort of..?

This video tells me this about the company: You're selling a bulb. Amazing. But the key aspect is missing.

You're not selling a bulb. You're selling a lifestyle. You're selling pearls dipped in honey. This video looks like you're selling colour changing five rupee bulbs to a marriage broker.

**Comment by kamakshidasan** [comment]
@cruzer3008 Is there an update here?

**Comment by maitri0411** [comment]
We have tried making it. You can have a look at the page and suggest if anything can be done.

**Comment by kamakshidasan** [comment]
Which page? qwerty.works?

**Comment by maitri0411** [comment]
http://joule.qwerty.works/Interns/index.html

**Comment by kamakshidasan** [comment]
The issue is still present. It looks exactly the same.

**Comment by kamakshidasan** [comment]
Can you remove the opacity?

**Comment by maitri0411** [comment]
We'll try changing it. But the idea was to make it look like an overlay on the video as in https://sleepyowl.co

**Comment by kamakshidasan** [comment]
Yes, I agree with that suggestion. There is a slight difference between
both the pages.

In sleepyowl's case, it is simply black+white video. However, in our case,
the richness of the colour matters a lot more.

In fact, I would suggest shooting just the landing page video again. Push
this request to the founders.

**Comment by cruzer3008** [comment]
We removed the opacity

**Comment by kamakshidasan** [comment]
The video shakes a bit towards the end. You may want to edit that part out.

**Comment by cruzer3008** [comment]
Done!!
