### ISSUE TITLE
Transition

### ISSUE THREAD

**Issue by kamakshidasan** [QwertyWorks/qwertyworks.github.io#18]
I see that there is a colour transition in one of elements, "Just say"...

a) Please increase the transition speed
b) Instead of using typical RGB colours for the text, you may want to take a look at this: https://clrs.cc/
This comment is especially, targeted towards "Yellow".
c) Please remove the capitalisation of text.

**Comment by kamakshidasan** [comment]
d) The font used in this section is not the default one used everywhere else.

**Comment by maitri0411** [comment]
Yeah, we'll make the appropriate changes.

**Comment by kamakshidasan** [comment]
e) Remove the quotation marks and instead make them italic.

**Comment by cruzer3008** [comment]
a) Transition speed doubled..Please suggest if that needs to be modified further
b) Changed the HexaCodes of the text colors ( Took them from the link suggested).
c) Capitalisation removed
d) Font made the same as on the rest of the page
e) Removed the same and made the text italic ( and bold as well )

**Comment by kamakshidasan** [comment]
Make the entire phrase as italic. Not just the colours' name.

Also think about making the correlation between the image on the left vs
transition text, a little more better.

**Comment by kamakshidasan** [comment]
It's good. Just add quotation marks.
