### ISSUE TITLE
"Download on the App Store" icon not showing up on the live website

### ISSUE THREAD

**Issue by cruzer3008** [QwertyWorks/qwertyworks.github.io#20]
The icon shows up properly on the locally hosted file , however fails to show up on the [live website](https://joule.qwerty.works/Interns/index.html)
Please help us if anyone has any idea regarding the same 
P.S the icon was downloaded from [here](https://developer.apple.com/app-store/marketing/guidelines/#section-badges) , the official apple website

The local version
![local](https://user-images.githubusercontent.com/31630057/44023721-d0c292de-9f08-11e8-93c8-6e25630b92cd.png)
The online version
![untitled](https://user-images.githubusercontent.com/31630057/44023729-d6a7036a-9f08-11e8-8d31-f44afdc95b0d.png)
Also this issue is prevalent on all instances wherein the AppStore icon has been used

**Comment by kamakshidasan** [comment]
You're supposed to solve the issues, not create new ones! :P

**Comment by cruzer3008** [comment]
I found this fascinating thus i did....

**Comment by kamakshidasan** [comment]
Haha - Chill -- solve solve solve

**Comment by kamakshidasan** [comment]
Yo. Check the console of the live website.

Either you have removed/renamed the file on the server of the live website.

**Comment by kamakshidasan** [comment]
I should be correct here. The file is named 'AppStore.png' on Github. Whereas on the live version, it is requesting for 'appStore.png'

**Comment by cruzer3008** [comment]
👏👏👏
Got it ...
But this is weird 
The locally hosted file on my system was appStore.png

**Comment by kamakshidasan** [comment]
Clear your cache and try again.
