### ISSUE TITLE
Flickering on hovering

### ISSUE THREAD

**Issue by kamakshidasan** [QwertyWorks/qwertyworks.github.io#21]
I see some readjustment of borders while hovering over the bulbs. Some sort flicker takes place. Can you check this out?

**Comment by cruzer3008** [comment]
Solved

**Comment by kamakshidasan** [comment]
Amazing! Closing this :)

**Comment by kamakshidasan** [comment]
Actually, nope. It still is present. I'm not closing this.

**Comment by kamakshidasan** [comment]
It happens the first time I hover over the bulb.

**Comment by maitri0411** [comment]
Its done. Check and confirm.

**Comment by kamakshidasan** [comment]
Perfect. Closing this issue.
