### ISSUE TITLE
Prefetching pages

### ISSUE THREAD

**Issue by kamakshidasan** [QwertyWorks/qwertyworks.github.io#24]
This might be a little advanced for you, but give it a shot if you want.

Have you noticed while playing videos in Youtube, when you want to play the next video, the entire page doesn't reload but only the video element changes? There is a small loading red bar at the top, which moves from left to right and only the video element refreshes.

It would be amazing if something similar could be done for all pages apart from the index page. Ideally, you should not be seeing the top navbar disappearing and appearing again.

This is not an issue but a feature request. There might be some learning curve involved here.

If you are willing to do this, tell me exactly how you are planning to do this and the relevant websites/tutorials, before you start.

**Comment by cruzer3008** [comment]
ContactUs page should now load faster
please check and confirm

**Comment by kamakshidasan** [comment]
Yes. Much better. What did you do?

**Comment by cruzer3008** [comment]
Compressed the background image
