### ISSUE TITLE
Mouse Scrolling

### ISSUE THREAD

**Issue by kamakshidasan** [QwertyWorks/qwertyworks.github.io#26]
Can you make mouse scrolling speed a little more faster on the customer segment page?

**Comment by maitri0411** [comment]
Made it a little faster. Check and confirm.

**Comment by kamakshidasan** [comment]
Nope. More smoother. Buttery smooth.

**Comment by maitri0411** [comment]
made it a little smoother.

**Comment by kamakshidasan** [comment]
Still feels the same. chuck it - it's not that important.
