### ISSUE TITLE
App store button

### ISSUE THREAD

**Issue by kamakshidasan** [QwertyWorks/qwertyworks.github.io#5]
It's always good practise to keep the app store buttons side by side.

Also, have you checked the efficiency of the website on mobile phones?

**Comment by cruzer3008** [comment]
App button placed side by side
Efficiency on mobile phones looks decent 
However we are still working on the desktop efficiency....

**Comment by kamakshidasan** [comment]
Cool. I will close this issue. We shall talk more about desktop efficiency in issue #7
