### ISSUE TITLE
Page speed statistics

### ISSUE THREAD

**Issue by kamakshidasan** [QwertyWorks/qwertyworks.github.io#7]
The website seems to be not optimized for desktop browsers. Can this be checked?

https://developers.google.com/speed/pagespeed/insights/

**Comment by kamakshidasan** [comment]
That's nice to hear! That improvement is surely promising. Can see if you
can minify any javascripts?

**Comment by cruzer3008** [comment]
It's showing 81 on Desktop and 92 on mobile as of now (owing to compressing images and minifying css and js files)

**Comment by kamakshidasan** [comment]
Yes - that's good. :)

I will close this issue for time being.
