### ISSUE TITLE
Mobile version has right aligned menus

### ISSUE THREAD

**Issue by kamakshidasan** [QwertyWorks/qwertyworks.github.io#9]
Look at the screenshots. Would it be possible to make them center aligned?

**Comment by kamakshidasan** [comment]
![photo_2018-07-17_13-20-42](https://user-images.githubusercontent.com/9362064/42814365-409d08d2-89c4-11e8-9918-f18bb5d523ae.jpg)

**Comment by cruzer3008** [comment]
Menu elements centre aligned

**Comment by kamakshidasan** [comment]
Yes - thank you. I will close this issue.
